url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "ananda f. smith" # the name of your site, e.g. ACME Corp.
description: "physics phd student @ mit"

collections:
  research:
    output: true
