menu:
- {name: 'home', url: '/'}
- {name: 'research', url: '/research'}
- {name: 'cv', url: '/ananda_smith_cv.pdf'}

# friends:
# - {name: 'josh', url: 'https://joshott.net'}
# - {name: 'verena', url: 'https://verenabellscheidt.github.io'}
# - {name: 'gemma', url: 'https://gemmahuai.github.io/'}
